### ISSUE TITLE
Crashes after changing input languages

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/translationKeyboard#46]
It's crashing on startup now so I can't submit a report from the app. I'll try to manually retrieve the logs and upload them later.

Device
---
Asus 8" 
Android 5.0
release: https://github.com/unfoldingWord-dev/translationKeyboard/releases/tag/2.1.0-beta5
Model: K012

Steps
---
* fresh install
* enabled tK
* changed input method to tK
* typed some text in the test input (en)
* added de and simplified Chinese as languages
* now at this point I can't remember if it crash as soon as I left the input language selections or after I clicked in the test input field.

**Comment by neutrinog** [comment]
Here's the helpful part of the stacktrace:

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.distantshoresmedia.keyboard.ch.a(int[])' on a null object reference
   at org.distantshoresmedia.keyboard.LatinIME.aa(Unknown Source)
   at org.distantshoresmedia.keyboard.LatinIME.onStartInputView(Unknown Source)
   ...
```

**Comment by neutrinog** [comment]
And here is the stacktrace I get when trying to reopen the app or when trying to open the keyboard elsewhere on the device.

```java
java.lang.NullPointerException at org.distantshoresmedia.keyboard.au.a(Unknown Source)
at org.distantshoresmedia.keyboard.BaseKeyboardView.setKeyboard(Unknown Source)
at org.distantshoresmedia.keyboard.TKKeyboardView.setKeyboard(Unknown Source)
at org.distantshoresmedia.keyboard.az.a(Unknown Source)
at org.distantshoresmedia.keyboard.az.a(Unknown Source)
at org.distantshoresmedia.keyboard.LatinIME.al(Unknown Source)
at org.distantshoresmedia.keyboard.LatinIME.onStartInputView(Unknown Source)
at android.inputmethodservice.InputMethodService.showWindowInner(InputMethodService.java:1474)
at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1432)
at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:427)
at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:203)
at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5253)
at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by bknatterud** [comment]
This should be fixed in next beta release coming in the next day.
