### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/translationKeyboard#48]
Environment
======
Environment Key | Value
:----: | :----:
version | 2.0.0
build | 83
UDID | 606b14409bcfd47
Android Release | 5.0.2
Android SDK | 21
Brand | samsung
Device | gt58wifi
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.distantshoresmedia.translationkeyboard/org.distantshoresmedia.activities.Main}: android.content.res.Resources$NotFoundException: String resource ID #0x7f0c019a
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
	at android.app.ActivityThread.access$900(ActivityThread.java:181)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6117)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f0c019a
	at android.content.res.Resources.getText(Resources.java:1347)
	at android.content.res.Resources.getString(Resources.java:1441)
	at android.content.Context.getString(Context.java:382)
	at org.distantshoresmedia.activities.Main.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6374)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
	... 10 more

```

**Comment by PeeJWeeJ** [comment]
Unable to reproduce, but should no longer rash in beta8
