### ISSUE TITLE
tried receiving via wifi direct

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/translationKeyboard#53]
Notes
======
tried receiving via wifi direct

Environment
======
Environment Key | Value
:----: | :----:
version | 2.0.0
build | 83
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.distantshoresmedia.translationkeyboard/org.distantshoresmedia.wifiDirect.WiFiDirectActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.access$900(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at org.distantshoresmedia.wifiDirect.WiFiDirectActivity.p(Unknown Source)
	at org.distantshoresmedia.wifiDirect.WiFiDirectActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6221)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
	... 10 more

```

**Comment by jag3773** [comment]
cf https://app.testfairy.com/projects/1338993-translationkeyboard/builds/1783763/sessions/4/?accessToken=ZZOEFYlINOTCA3TUvrJLckvMfjU

**Comment by PeeJWeeJ** [comment]
Unable to reproduce, but should no longer crash in beta8
