### ISSUE TITLE
trird sharing via bluetooth

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/translationKeyboard#55]
Notes
======
trird sharing via bluetooth

Environment
======
Environment Key | Value
:----: | :----:
version | 2.0.0
build | 83
UDID | 9d1aa51f1c1fcb85
Android Release | 4.4.3
Android SDK | 19
Brand | Amazon
Device | ariel
Stack trace
======
```java
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.bluetooth/com.android.bluetooth.opp.BluetoothOppLauncherActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1633)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
	at android.app.Activity.startActivityForResult(Activity.java:3456)
	at android.app.Activity.startActivityForResult(Activity.java:3417)
	at android.support.v4.app.o.startActivityForResult(Unknown Source)
	at org.distantshoresmedia.e.k.d(Unknown Source)
	at org.distantshoresmedia.e.k.b(Unknown Source)
	at org.distantshoresmedia.e.o.onClick(Unknown Source)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5266)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by PeeJWeeJ** [comment]
I believe this is fixed in beta8, assuming it's not an Amazon specific issue. Re-open if it occurs again.
